### PR TITLE
fix bug: realtime will lost connection after inactive 5m

### PR DESCRIPTION
**Pull request by shynome**
this bug is because [r3labs/sse](http://github.com/r3labs/sse) client can't dial the remote server close event, so I replace another sse client [donovanhide/eventsource](http://github.com/donovanhide/eventsource) , and retry connection manual

### CODE REVIEW

**Comment by shynome** [comment]
localhost test is pass, why ci failed?

**Comment by shynome** [comment]
I gave up after trying my best, can you help me find out what's wrong

**Comment by shynome** [comment]
I think waiting for zero time to retry is too fast, pocketbase server will crash? My pocketbase server is panicking with too much memory stack and I'm still looking for the reason

**Comment by r--w** [comment]
I'll try to take a look, but no guarantees when.

**Comment by r--w** [comment]
so I spent a few minutes, and it seems that after skipping `TestCollection_Unsubscribe`, Github actions are happy [/actions/runs/3744462920](https://github.com/r--w/pocketbase/actions/runs/3744462920)

**Comment by shynome** [comment]
Finally I found out that the problem is that the create event is dispatched, but the stream is not ready yet, adding wait for the stream to be ready does the trick.

I create another pr for the merge

**Pull request closed without merging**
